version: '3.3'
services:
    grafana:
        image: grafana/grafana:9.4.3
        container_name: grafana
        #restart: always
        ports:
            - '3000:3000'
        volumes:
            - './storage/grafana/data:/var/lib/grafana'
            - './storage/grafana/provisioning:/etc/grafana/provisioning/'
            - './storage/grafana/dashboards:/tmp/dashboards/'

    influxdb:
        image: influxdb:2.6-alpine
        container_name: influxdb
        #restart: always
        ports:
            - '8086:8086'
        environment:
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=admin
            - DOCKER_INFLUXDB_INIT_PASSWORD=password
            - DOCKER_INFLUXDB_INIT_ORG=f1
            - DOCKER_INFLUXDB_INIT_BUCKET=data
            - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=LoOFvHw1tUXrUZ8oUqaozmEjxxG9UNO5H5YfRI4cGu306xwQVu_KMNxRYRMrWbhdD886N2PuRgpo9v4v_58pHw==
        volumes:
            - './storage/influxdb:/var/lib/influxdb2'
